//
// Given two strings s and t which consist of only lowercase letters.
//
// String t is generated by random shuffling string s and then add one more letter at a random position.
//
// Find the letter that was added in t.
//
// Example:
//
// Input:
// s = "abcd"
// t = "abcde"
//
// Output:
// e
//
// Explanation:
// 'e' is the letter that was added.
//


class Solution {
public:
    char findTheDifference(string s, string t) {
        //因为被重排，如果你再重排，就有点无赖了。
        //直接考虑哈希表，st两者遍历一次即可,最后遍历一次map，显然是O1
        unordered_map<char,int> col;
        for(int i=0;i<s.size();++i){
            col[s[i]]++;
        }
        for(int i=0;i<t.size();++i){
            col[t[i]]--;
        }
        for(auto iter=col.begin();iter!=col.end();++iter)
            if(iter->second==-1)
                return iter->first;
        static char c=' ';
        return c;
        
        
    }
};
